### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by theryecatcher**
Relates to #125.

Adding support for building the app using Docker and using docker-compose to do so.    
Kindly Review.

### CODE REVIEW

**Comment by devfake** [comment]
First of all many thanks for the work!

I tried to get it to work. But I get the following message, and then the script aborts: https://pastebin.com/S9tUz3aD

I'm using Windows 10 and Docker 18.09.1 (Compose 1.23.2).

Redis is also missing (for imports and refresh data). Is there a way to remove the hardcoded credentials from `docker-compose.yml`? A seperate env file?

**Comment by theryecatcher** [comment]
Thanks for looking into it, weird haven't seen that error before. Will try it out on Windows too. Will add Redis, wasn't sure if it was necessary or an option so had kept it out.

**Comment by FuzzyMistborn** [comment]
I got this to build successfully but can't get the DB to connect.  I'm running v2 of docker-compose but i've made the necessary changes that it should work.  I've also tested my connection/credentials from outside the container and it works fine.

Log:
```
+ id -u www-data,
+ '[' '!' -e /var/www/html/backend/.env ']',
+ echo '[flox first install]',
+ mysql_host=mysql,
+ mysql_port=3309,
+ /wait-for-it.sh mysql:3309 -t 120 -- /init-run.sh,
[flox first install],
wait-for-it.sh: waiting 120 seconds for mysql:3309,
wait-for-it.sh: timeout occurred after waiting 120 seconds for mysql:3309,
CREATING .ENV FILE,
GENERATING APP KEY,
TRYING TO MIGRATE DATABASE,
Can not connect to the database. Error: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = flox and table_name = migrations and table_type = 'BASE TABLE'),
Make sure your database credentials in .env are correct,
```

Docker-compose (modified a few things for privacy):
```
version: '2'
services:
  flox:
    container_name: flox
    image: flox:latest
    build:
      dockerfile: /home/fuzzy/docker/flox/Dockerfile
      context: ./flox/
    networks:
      - internal
    ports:
     - "8888:80"
    environment:
     - APACHE_DOCUMENT_ROOT=/var/www/html/public
     - APACHE_RUN_USER=www-data
     - APACHE_RUN_GROUP=www-data
     - APACHE_RUN_USER_ID=33
     - APACHE_RUN_GROUP_ID=33
     - FLOX_DB_NAME=flox 
     - FLOX_DB_USER=fuzzy
     - FLOX_DB_PASS=flox
     - FLOX_DB_HOST=mysql 
     - FLOX_DB_PORT=3309
     - TMDB_API_KEY=xxxxxx
     - FLOX_ADMIN_USER=fuzzy
     - FLOX_ADMIN_PASS=fuzzy123
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports: ["3309:3306"]
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: fuzzy123
      MYSQL_DATABASE: flox
      MYSQL_USER: fuzzy
      MYSQL_PASSWORD: flox
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - /home/fuzzy/docker/flox/mysql:/var/lib/mysql
networks:
  internal:
```

**Comment by FuzzyMistborn** [comment]
Nevermind, as soon as I posted I realized it was UFW....sigh.

**Comment by FuzzyMistborn** [comment]
Adding the ability to mount the /var/www/html volume outside of the container would be a nice addition.

**Comment by nazarimilad** [comment]
Any update on the docker support?

**Comment by armdan** [comment]
any hopes we can have docker support?

**Comment by devfake** [comment]
Sorry for the much too late reply. I will close the PR because i will completely redevelop Flox. In the next version, there will be docker support included.

**Pull request closed without merging**
